# Env definition file for creating environment via conda

name: simple-env
channels:
 - conda-forge
dependencies:
 - python>=3.11
 - iris>=3.0
 - numpy
 - nctoolkit
 - cdo
 - black
 - pre-commit
 - humanize
 - coverage
 - pytest
 - pytest-cov
 - myst-parser
 - sphinx
 - sphinx_rtd_theme
 - sphinx-argparse
 - sphinx-gallery
 - sphinxcontrib-mermaid
 - numpydoc
 - pipreqs
 - pandas
 - geopandas
 - setuptools>=45
 - setuptools_scm>=6.2
 - calver  # CalVer package versioning
 - pip
