#!/bin/bash

#######################################################################################
# Script to run all system tests
# Invoking tests via pytest
# Called imported code will differ if local editable vs user install
#######################################################################################

# Source code, variables from common.sh
# Makes CODE_DIR etc available. Also sources common/common.sh
source common.sh
echo "Current working directory: ${PWD}"
# Discover and run tests on code path. Options include:
# -v verbose flag, -r displays “short test summary info” at end of session,
# -A lists all info
# --tb traceback print mode (auto/long/short/line/native/no)., e.g. --tb=long

echo "Move to test dir and run pytest: ${TESTS_DIR}"
cd "${TESTS_DIR}"/a_unit/demos
pytest test_demo_logs.py --tb=long -vrA


#echo "Move to test dir and run pytest: ${TESTS_DIR}"
#cd "${TESTS_DIR}"/b_integration
#pytest test_logging.py --tb=long -vrA

#######################################################################################
# Code review and system context notes
# ====================================
# This script is used during manual testing
# Not called by any other scripts,
# not used as part of the GitHub actions automated tests
# Config options
#   - currently the pyproject.toml options take precedence over these script options
#   - retained here so later the config in pyproject.toml can be relaxed or removed
#######################################################################################
